name: Oxygen Validation Script
description: Validate your files using Oxygen Scripting
branding:
  icon: 'check-square'
  color: 'blue'
inputs:
  validationDir:
    description: The name of directory containing the files to be validated.
    required: true
    default: validation
  licenseKey:
    description: Oxygen Scripting license key.
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout current repo.
      uses: actions/checkout@v3
    - name: Checkout Oxygen Scripting Template repo.
      uses: actions/checkout@v3
      with:
        repository: https://github.com/oxygenxml/oxygen-sample-validation-script
        path: scripting

    # Validate wrapper
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1.0.4

    # Setup Java 11 environment for the next steps
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11

    - name: Make gradlew executable
      run: chmod +x ./scripting/build/gradlew
      shell: bash

    - name: Build with Gradle
      run: cd scripting; cd build; ./gradlew runValidation -PvalidationDir=${{ github.event.inputs.validationDir }} -PlicenseKey=${{ github.event.inputs.licenseKey }} --info --stacktrace
      shell: bash

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        folder: report # The folder the action should deploy.