name: Validate Script

on:
  push:
    branches: [ main ]    
  pull_request:  
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
        - name: Fetch Sources
          uses: actions/checkout@v3

        # Validate wrapper
        - name: Gradle Wrapper Validation
          uses: gradle/wrapper-validation-action@v1.0.4

        # Setup Java 11 environment for the next steps
        - name: Setup Java
          uses: actions/setup-java@v3
          with:
            distribution: zulu
            java-version: 11
        - name: Make gradlew executable
          run: chmod +x ./build/gradlew
        - name: Build with Gradle
          env: # Or as an environment variable
           SCRIPTING_LICENSE_KEY: ${{secrets.SCRIPTING_LICENSE_KEY}}
          run: cd build; ./gradlew --info --stacktrace

        - name: Deploy 🚀
            uses: JamesIves/github-pages-deploy-action@v4
            with:
              folder: build # The folder the action should deploy.
